name: 'AI Spec Converter'
description: 'This action converts AI specifications to different formats.'
inputs:
  konnect_token:  # id of input
    description: 'Konnect API token for authentication'
    required: true
  source_format:  # id of input
    description: 'Source format of the AI specification'
    required: true
    default: 'wsdl'
  source_file:  # id of input
    description: 'Path to the source AI specification file'
    required: true
outputs:
  service-id:
    description: "Service ID"
    value: ${{ steps.create_service.outputs.service_id }}
runs:
  using: "composite"
  steps:
      - name: Install HTTPie
        shell: bash
        run: |
          curl -SsL https://packages.httpie.io/deb/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/httpie.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" | sudo tee /etc/apt/sources.list.d/httpie.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Generate Markdown Documentation
        shell: bash
        run: |
          pip install requests
          cat ${{ inputs.source-file }} | python $GITHUB_WORKSPACE/service-catalog/ai-convert.py --template raml > /tmp/raml.md

      - name: Create Service Catalog Entry
        id: create_service
        shell: bash
        run: |
          payload=`http POST $BASE_SERVICE_HUB_URL/services Authorization:"Bearer ${{ inputs.konnect_token }}" < $GITHUB_WORKSPACE/service-catalog/raml-service.json`
          echo "service_id=$(echo $payload | jq -r '.id')" >> $GITHUB_OUTPUT
      - name: Attach Documentation to Service
        shell: bash
        run: |
          export raw_content=`cat /tmp/raml.md| base64 -w0` ; cat $GITHUB_WORKSPACE/service-catalog/raml-documentation.json | envsubst '$raw_content' > /tmp/raml-documentation.json
          http POST "$BASE_SERVICE_HUB_URL/services/${{ steps.create_service.outputs.service_id }}/documents" Authorization:"Bearer ${{ inputs.konnect_token }}" < /tmp/raml-documentation.json
